services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3305:3306'
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -u${MYSQL_USER} -p${MYSQL_PASSWORD}']
      interval: 10s
      timeout: 5s
      retries: 5
  api-service:
    container_name: api-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_PORT=${NODE_PORT}
      - NODE_ENV=${NODE_ENV}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - API_BASE_URL=${APP_BASE_URL}
      - PAYSTACK_API_KEY=${PAYSTACK_API_KEY}

    ports:
      - '8281:8282'
    depends_on:
      mysql:
        condition: service_healthy
